# Global settings
project_name: "aDNA_Project"

pipeline:
  global:
    skip_existing_files: true

  raw_reads_processing:
    execute: true
    quality_checking_raw:
      execute: true
    adapter_removal:
      execute: true
      settings:
        min_quality: 0
        min_length: 0
        adapters_sequences:
          r1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
          r2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" 
    quality_checking_trimmed:
      execute: true
    quality_filtering:
      execute: true
      settings:
        min_quality: 25
        min_length: 30
    quality_checking_quality_filtered:
      execute: true
    quality_checking_merged:
      execute: true
    contamination_analysis:
      execute: true
      tools:
        ecmsd:
          execute: true
          settings:
            conda_env: "../../../../envs/ecmsd.yaml"
            executable: "/mnt/data2/sarah/app_ecmsd/shell/ECMSD.sh"
        centrifuge:
          execute: true
          settings:
            conda_env: "../../../../envs/centrifuge.yaml"
            index: "/mnt/data5/sarah/app_centrifuge/centrifuge_index/p+h+v"
    statistical_analysis:
      execute: true

  reference_processing:
    execute: true
    deduplication:
      execute: true
    damage_rescaling:
      execute: true
    damage_analysis:
      execute: true
    endogenous_reads_analysis: 
      execute: true
    coverage_analysis: 
      execute: true

# Species-specific settings
species:
  Bger:
    name: "Blattella germanica"
#  Dbus:
#    name: "Drosophila busckii"