# config.yaml - Configuration file for aDNA pipeline
# Global settings
project_name: "aDNA_Project"

pipeline:
  raw_reads_processing:
    execute: false
    quality_checking_raw:
      execute: true
    adapter_removal:
      execute: true
      settings: 
        adapters_sequences:
          r1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
          r2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" 
    quality_checking_trimmed:
      execute: true
    quality_filtering:
      execute: true
    quality_checking_quality_filtered:
      execute: true
    contamination_analysis:
      execute: true
      tools:
        centrifuge:
          execute: true
          settings:
            conda_env: "../../../../envs/centrifuge.yaml"
            executable: "centrifuge"
            database: "/mnt/data5/sarah/aDNA/centrifuge_db"
        kraken: 
          execute: true
          settings:
            conda_env: "../../../../envs/kraken.yaml"
            executable: "kraken"
            database: "/mnt/data5/sarah/aDNA/kraken_db"
        ecmsd:
          execute: true
          settings:
            conda_env: "../../../../envs/ecmsd.yaml"
            executable: "/mnt/data2/sarah/app_ecmsd/shell/ECMSD.sh"
    statistical_analysis:
      execute: true

  reference_genome_processing:
    execute: true
    map_reads_to_reference_genome:
      execute: true
    damage_analysis:
      execute: true
    create_consensus_sequence:
      execute: true
    endogenous_reads_analysis: 
      execute: true
    coverage_analysis: 
      execute: true

# Species-specific settings
species:
# data2:
  tDcar:
    name: "Drosophila cardini"
  tDbus:
    name: "Drosophila busckii"
  tDfun:
    name: "Drosophila funebris"
  tDimm:
    name: "Drosophila immigrans"
  tDrep:
    name: "Drosophila repleta"
  tDmer:
    name: "Drosophila mercatorum"
  tDwil:
    name: "Drosophila willistoni"
  tDana:
    name: "Drosophila annanasae"
  tBger:
    name: "Blattella germanica"
  tBgerRun1:
    name: "Blattella germanica"
  tTni:
    name: "Trichoplusia ni"
  tOcap:
    name: "Ophyra capensis"
  tLlit:
    name: "Littorina littorea"
  tPvul:
    name: "Patella vulgata"
  tPhum:
    name: "Pediculus humuanus"

# data5:
#species:
  Bger:
    name: "Blattella germanica"
  Mmus:
    name: "Mus musculus"
  Dsim:
    name: "Drosophila simulans"
  Dmel:
    name: "Drosophila melanogaster"
  Dbus:
    name: "Drosophila busckii"
  Dfun:
    name: "Drosophila funebris"
  Dhis:
    name: "Drosophila histrio"
  Dimm:
    name: "Drosophila immigrans"
  Drep:
    name: "Drosophila repleta"
  trial_Bger:
    name: "Trial Blattella germanica"
  trial_Dsim:
    name: "Trial Drosophila simulans"
  trial_Phortica:
    name: "Trial Phortica"
  trial_Sepsis:
    name: "Trial Sepsis"
  trial_Mmus:
    name: "Trial Mus musculus"
  trial_Dmel:
    name: "Trial Drosophila melanogaster"
  trial_spike_Dsim:
    name: "Trial Spike Drosophila simulans"
  trial_Dbus:
    name: "Trial Drosophila busckii"
  trial_Dfun:
    name: "Trial Drosophila funebris"
  trial_Dhis:
    name: "Trial Drosophila histrio"
  trial_Dimm:
    name: "Trial Drosophila immigrans"
  trial_Drep:
    name: "Trial Drosophila repleta"
